FROM node:18

COPY ./scripts/wait-for-it.sh /usr/local/bin/

RUN sed -i 's/\r$//' /usr/local/bin/wait-for-it.sh && chmod +x /usr/local/bin/wait-for-it.sh

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8080

CMD ["node", "src/app.js"]