// @ts-check

/**
 * Sidebar configuration for Docusaurus.
 * 
 * You can define static sidebars for each language separately
 * by using explicit labels.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  fr: [
    {
      type: 'category',
      label: 'Architecture',
      items: ['global-architecture', 'physical-architecture', 'logical-architecture', 'data-flows', 'security', 'MVP'],
    },
    {
      type: 'category',
      label: 'Conventions',
      items: ['git-convention', 'doc-convention', 'coding-convention'],
    },
    {
      type: 'category',
      label: 'Sécurité',
      items: ['general-security'],
    },
    {
      type: 'category',
      label: 'Utiles',
      items: ['install-workspace', 'templates-usage']
    },
    {
      type: 'category',
      label: 'Documentation API',
      items: [
        {
          type: 'category',
          label: 'Gateway API',
          items: [{ type: 'autogenerated', dirName: 'api/gateway' }],
        },
        {
          type: 'category',
          label: 'User API',
          items: [{ type: 'autogenerated', dirName: 'api/user' }],
        },
        {
          type: 'category',
          label: 'Asset API',
          items: [{ type: 'autogenerated', dirName: 'api/asset' }],
        },
        {
          type: 'category',
          label: 'Map API',
          items: [{ type: 'autogenerated', dirName: 'api/map' }],
        },
      ],
    },
  ],
  en: [
    {
      type: 'category',
      label: 'Conventions',
      items: ['en/git-convention', 'en/doc-convention', 'en/coding-convention', 'en/templates_usage'],
    },
    {
      type: 'category',
      label: 'Security',
      items: ['en/general-security', 'en/data-protection', 'en/secrets-management', 'en/access-control', 'en/cicd-security'],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['en/architecture'],
    }
  ],
};

module.exports = sidebars;


export default sidebars;
